<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Users\Queries\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappings\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcommerceBackend.Domain\EcommerceBackend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MessagesEn.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesEn.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MessagesEn.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesEn.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
